export enum WORLD_BANK_INDICATOR {
  GDP_GROWTH = 'NY.GDP.MKTP.KD.ZG',
  GDP = 'NY.GDP.MKTP.CD',
  GDP_PER_CAPITA = 'NY.GDP.PCAP.CD',
  INFLATION = 'FP.CPI.TOTL.ZG',
  UNEMPLOYMENT = 'SL.UEM.TOTL.ZS',
}
